"""Idempotently seed the initial 40-paper Deep Dive reading pool."""

from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "papers" / "catalog.yaml"
AS_OF = "2026-07-18"


def paper(
    paper_id: str,
    title: str,
    year: int,
    version_date: str,
    arxiv_id: str,
    topics: list[str],
    prerequisites: list[str],
    claim: str,
    evidence: str,
    limitation: str,
    relations: list[dict[str, str]],
    *,
    code_url: str = "",
    source_type: str = "peer_reviewed",
    reproduction: str = "planned-small",
) -> dict:
    return {
        "id": paper_id,
        "title": title,
        "year": year,
        "version_date": version_date,
        "source_type": source_type,
        "url": f"https://arxiv.org/abs/{arxiv_id}",
        "code_url": code_url,
        "topics": topics,
        "tier": "deep_dive",
        "status": "unread",
        "prerequisites": prerequisites,
        "claims": [claim],
        "evidence": [evidence],
        "limitations": [limitation],
        "reproduction": reproduction,
        "relations": relations,
        "as_of": AS_OF,
    }


EXTRA_PAPERS = [
    paper(
        "mqa",
        "Fast Transformer Decoding: One Write-Head is All You Need",
        2019,
        "2019-11-06",
        "1911.02150",
        ["attention", "mqa", "kv-cache"],
        ["transformer", "kv-cache", "tensor-shapes"],
        "所有查询头共享单组 K/V，可显著减少自回归解码的缓存和内存带宽。",
        "机器翻译解码质量、延迟和带宽需求的比较。",
        "共享 K/V 可能损失质量，现代模型常以 GQA 折中。",
        [{"type": "improves", "target": "transformer"}],
        reproduction="required-cache",
    ),
    paper(
        "transformer_xl",
        "Transformer-XL: Attentive Language Models Beyond a Fixed-Length Context",
        2019,
        "2019-01-09",
        "1901.02860",
        ["long-context", "recurrence", "relative-position"],
        ["transformer", "language-modeling"],
        "跨片段状态复用和相对位置编码可突破固定训练片段的上下文边界。",
        "语言建模困惑度、有效上下文长度和生成速度实验。",
        "缓存状态通常停止梯度，且训练与推理状态管理更复杂。",
        [{"type": "improves", "target": "transformer"}],
    ),
    paper(
        "alibi",
        "Train Short, Test Long: Attention with Linear Biases Enables Input Length Extrapolation",
        2022,
        "2021-08-27",
        "2108.12409",
        ["position-encoding", "length-extrapolation", "attention"],
        ["transformer", "causal-attention"],
        "对注意力分数加入按距离线性衰减的头相关偏置，可省去位置向量并改善长度外推。",
        "在短序列训练、长序列测试下比较困惑度和效率。",
        "外推效果依任务与训练长度而变，不能等同于真正掌握无限上下文。",
        [{"type": "contrasts_with", "target": "rope"}],
        reproduction="required-bias",
    ),
    paper(
        "longformer",
        "Longformer: The Long-Document Transformer",
        2020,
        "2020-04-10",
        "2004.05150",
        ["sparse-attention", "sliding-window", "long-context"],
        ["transformer", "attention-mask"],
        "局部滑窗加少量全局 token 可把长文档注意力复杂度降为近似线性。",
        "长文档语言建模与问答、分类任务对比。",
        "稀疏模式是先验，跨窗口信息需多层传播或全局位置。",
        [{"type": "contrasts_with", "target": "transformer"}],
        code_url="https://github.com/allenai/longformer",
        reproduction="required-mask",
    ),
    paper(
        "bigbird",
        "Big Bird: Transformers for Longer Sequences",
        2020,
        "2020-07-28",
        "2007.14062",
        ["sparse-attention", "random-attention", "long-context"],
        ["longformer", "graph-connectivity"],
        "局部、随机与全局连接组合在降低复杂度的同时保留较强表达能力。",
        "理论分析以及长序列 NLP 与基因组任务实验。",
        "随机稀疏模式的实际内核效率和任务适配并不由渐近复杂度保证。",
        [{"type": "improves", "target": "longformer"}],
    ),
    paper(
        "reformer",
        "Reformer: The Efficient Transformer",
        2020,
        "2020-01-13",
        "2001.04451",
        ["lsh-attention", "reversible-layers", "memory"],
        ["transformer", "hashing"],
        "LSH 注意力与可逆残差层可降低长序列训练的注意力和激活内存。",
        "长序列语言与图像生成上的内存、速度和质量实验。",
        "哈希分桶近似、实现复杂度和硬件利用率会影响真实收益。",
        [{"type": "contrasts_with", "target": "transformer"}],
        code_url="https://github.com/google/trax",
    ),
    paper(
        "performer",
        "Rethinking Attention with Performers",
        2021,
        "2020-09-30",
        "2009.14794",
        ["linear-attention", "kernel", "random-features"],
        ["softmax-attention", "probability", "kernels"],
        "正随机特征可近似 softmax 注意力并把时间与空间复杂度降为线性。",
        "多模态任务上的近似误差、质量、速度和内存对比。",
        "随机特征数决定误差与成本，短序列或优化内核上未必更快。",
        [{"type": "contrasts_with", "target": "transformer"}],
        reproduction="required-kernel",
    ),
    paper(
        "linear_transformer",
        "Transformers are RNNs: Fast Autoregressive Transformers with Linear Attention",
        2020,
        "2020-06-29",
        "2006.16236",
        ["linear-attention", "recurrent-state", "kernel"],
        ["transformer", "associativity"],
        "利用核特征和矩阵乘法结合律，注意力可写成并行训练与递归解码两种形式。",
        "序列任务上的速度、内存和质量比较。",
        "替代相似度并非精确 softmax，状态容量和数值稳定性可能受限。",
        [{"type": "contrasts_with", "target": "transformer"}],
        reproduction="required-recurrence",
    ),
    paper(
        "retnet",
        "Retentive Network: A Successor to Transformer for Large Language Models",
        2023,
        "2023-07-17",
        "2307.08621",
        ["retention", "linear-attention", "recurrent-state"],
        ["linear-attention", "rope", "decay"],
        "Retention 提供并行、递归和分块递归三种等价计算形式。",
        "不同模型规模的语言建模质量、吞吐、延迟和内存比较。",
        "结论依赖定制实现，训练稳定性和状态遗忘仍需任务化评估。",
        [{"type": "improves", "target": "linear_transformer"}],
        code_url="https://github.com/microsoft/unilm/tree/master/retnet",
    ),
    paper(
        "mamba",
        "Mamba: Linear-Time Sequence Modeling with Selective State Spaces",
        2023,
        "2023-12-01",
        "2312.00752",
        ["state-space-model", "selective-scan", "long-context"],
        ["recurrence", "state-space-model", "parallel-scan"],
        "输入依赖的选择性状态更新可改善固定 SSM 难以进行内容寻址的问题。",
        "语言、音频和基因组任务上的质量与吞吐比较。",
        "性能依赖融合扫描内核，固定状态仍可能压缩或遗忘细节。",
        [{"type": "contrasts_with", "target": "transformer"}],
        code_url="https://github.com/state-spaces/mamba",
        reproduction="selective-state-small",
    ),
    paper(
        "h3",
        "Hungry Hungry Hippos: Towards Language Modeling with State Space Models",
        2022,
        "2022-12-28",
        "2212.14052",
        ["state-space-model", "long-convolution", "language-modeling"],
        ["transformer", "convolution", "recurrence"],
        "专为语言设计的 SSM 层可弥补早期状态空间模型在复制和归纳任务上的弱点。",
        "语言建模、合成任务和混合注意力架构实验。",
        "纯 SSM 与混合结果需区分，长卷积的高效实现有硬件依赖。",
        [{"type": "contrasts_with", "target": "transformer"}],
    ),
    paper(
        "hyena",
        "Hyena Hierarchy: Towards Larger Convolutional Language Models",
        2023,
        "2023-02-21",
        "2302.10866",
        ["long-convolution", "implicit-filter", "sequence-model"],
        ["convolution", "gating", "transformer"],
        "长卷积与数据控制门可形成次二次的注意力替代序列算子。",
        "大规模语言建模、上下文长度和墙钟效率实验。",
        "质量与效率同时依赖隐式滤波器、训练配方和优化实现。",
        [{"type": "contrasts_with", "target": "transformer"}],
        code_url="https://github.com/HazyResearch/safari",
    ),
    paper(
        "flashattention3",
        "FlashAttention-3: Fast and Accurate Attention with Asynchrony and Low-precision",
        2024,
        "2024-07-11",
        "2407.08608",
        ["flashattention", "hopper", "low-precision"],
        ["flashattention2", "gpu-memory", "numerical-error"],
        "异步流水、warp 专门化与低精度方案可进一步提高 Hopper GPU 注意力利用率。",
        "H100 上的内核吞吐、端到端速度和数值误差实验。",
        "强依赖 Hopper 硬件，CPU 学习只能复现分块与数值思想。",
        [{"type": "improves", "target": "flashattention2"}],
        code_url="https://github.com/Dao-AILab/flash-attention",
        reproduction="optional-gpu",
    ),
    paper(
        "ring_attention",
        "Ring Attention with Blockwise Transformers for Near-Infinite Context",
        2023,
        "2023-10-03",
        "2310.01889",
        ["distributed-attention", "long-context", "ring-communication"],
        ["flashattention", "distributed-training"],
        "沿设备环传递 K/V 分块，可把通信与块注意力计算重叠并扩展上下文。",
        "多设备长上下文训练的可扩展性和语言任务实验。",
        "需要多设备且受互连拓扑影响，不是单机注意力复杂度的消除。",
        [{"type": "builds_on", "target": "flashattention"}],
        reproduction="conceptual",
    ),
    paper(
        "stripedhyena",
        "StripedHyena: Moving Beyond Transformers with Hybrid Signal Processing Models",
        2024,
        "2024-02-06",
        "2402.04253",
        ["hybrid-architecture", "hyena", "long-context"],
        ["hyena", "attention", "architecture"],
        "交错 Hyena 与注意力层可在长上下文效率和内容检索能力间折中。",
        "开放模型的语言基准、长上下文和推理效率评测。",
        "混合层和完整训练配方共同变化，单组件归因有限。",
        [{"type": "builds_on", "target": "hyena"}],
        source_type="technical_report",
        reproduction="architecture-analysis",
    ),
    paper(
        "base_layers",
        "BASE Layers: Simplifying Training of Large, Sparse Models",
        2021,
        "2021-03-30",
        "2103.16716",
        ["moe", "balanced-assignment", "routing"],
        ["sparsely-gated-moe", "assignment-problem"],
        "把路由写成平衡分配问题可在不使用辅助均衡损失时实现专家容量利用。",
        "语言模型规模化、负载和训练稳定性实验。",
        "全局平衡分配涉及通信，在线推理和小批次行为不同。",
        [{"type": "improves", "target": "sparsely_gated_moe"}],
        code_url="https://github.com/facebookresearch/fairseq",
    ),
    paper(
        "expert_choice",
        "Mixture-of-Experts with Expert Choice Routing",
        2022,
        "2022-02-18",
        "2202.09368",
        ["moe", "expert-choice", "routing"],
        ["switch-transformer", "top-k"],
        "由专家选择固定数量 token 可天然控制容量并允许每个 token 使用可变专家数。",
        "语言模型预训练的收敛速度、质量和负载比较。",
        "路由依赖批次全局选择，对因果在线推理和分布式实现有约束。",
        [{"type": "contrasts_with", "target": "switch_transformer"}],
        reproduction="routing-small",
    ),
    paper(
        "sparse_upcycling",
        "Sparse Upcycling: Training Mixture-of-Experts from Dense Checkpoints",
        2022,
        "2022-12-09",
        "2212.05055",
        ["moe", "upcycling", "pretraining"],
        ["switch-transformer", "checkpoint"],
        "复制 Dense FFN 为专家并继续稀疏训练，可复用已有计算而不从头训练 MoE。",
        "视觉与语言模型的训练预算、质量和扩展实验。",
        "初始专家相同会影响专门化，收益依继续训练 token 数。",
        [{"type": "builds_on", "target": "switch_transformer"}],
        reproduction="required-small",
    ),
    paper(
        "megablocks",
        "MegaBlocks: Efficient Sparse Training with Mixture-of-Experts",
        2023,
        "2022-11-29",
        "2211.15841",
        ["moe", "block-sparse", "systems"],
        ["switch-transformer", "gpu-kernels", "capacity"],
        "块稀疏算子可避免因容量截断而丢弃 token，并提高不规则 MoE 计算效率。",
        "GPU 内核、端到端训练吞吐和模型质量实验。",
        "系统收益依 GPU 与分布式栈，CPU 只能验证无 token dropping 的语义。",
        [{"type": "improves", "target": "switch_transformer"}],
        code_url="https://github.com/databricks/megablocks",
        reproduction="optional-gpu",
    ),
    paper(
        "deepspeed_moe",
        "DeepSpeed-MoE: Advancing Mixture-of-Experts Inference and Training to Power Next-Generation AI Scale",  # noqa: E501
        2022,
        "2022-01-14",
        "2201.05596",
        ["moe", "expert-parallelism", "inference"],
        ["gshard", "distributed-training", "all-to-all"],
        "专家并行、分层通信和推理切分可改善大规模 MoE 的训练与服务效率。",
        "多节点训练和推理吞吐、延迟与扩展性实验。",
        "依赖特定集群和软件栈，缩尺实现不能验证全部通信结论。",
        [{"type": "builds_on", "target": "gshard"}],
        code_url="https://github.com/microsoft/DeepSpeed",
        reproduction="conceptual",
    ),
    paper(
        "dedup_training_data",
        "Deduplicating Training Data Makes Language Models Better",
        2022,
        "2021-07-14",
        "2107.06499",
        ["data", "deduplication", "memorization"],
        ["pretraining-data", "hashing", "evaluation"],
        "文档级与局部重复会造成记忆和评测污染，去重可改善有效训练效率。",
        "不同去重策略下的语言建模、生成记忆和污染实验。",
        "去重阈值会删掉合法重复内容，结论依语料域和检测方法。",
        [{"type": "builds_on", "target": "gpt3"}],
        reproduction="required-minhash",
    ),
    paper(
        "the_pile",
        "The Pile: An 800GB Dataset of Diverse Text for Language Modeling",
        2020,
        "2020-12-31",
        "2101.00027",
        ["data", "dataset", "pretraining"],
        ["language-modeling", "data-mixture"],
        "公开、多来源且记录组成的语料可支持可审计的语言模型训练研究。",
        "数据组成分析以及在不同 Pile 子集上的模型评测。",
        "许可、隐私、重复和来源偏差仍需单独治理，规模不代表质量。",
        [],
        code_url="https://github.com/EleutherAI/the-pile",
        source_type="technical_report",
        reproduction="data-audit",
    ),
    paper(
        "gopher",
        "Scaling Language Models: Methods, Analysis & Insights from Training Gopher",
        2021,
        "2021-12-22",
        "2112.11446",
        ["pretraining", "scaling", "evaluation"],
        ["gpt3", "scaling-laws", "benchmarking"],
        "系统改变规模、数据与评测可揭示大模型能力、偏差和失败模式。",
        "多规模模型在广泛任务、安全和记忆分析上的结果。",
        "训练数据和计算不可低成本复现，基准提升并非统一能力证明。",
        [{"type": "improves", "target": "gpt3"}],
        source_type="technical_report",
        reproduction="scaling-analysis",
    ),
    paper(
        "mmlu",
        "Measuring Massive Multitask Language Understanding",
        2021,
        "2020-09-07",
        "2009.03300",
        ["evaluation", "knowledge", "few-shot"],
        ["gpt3", "prompting", "statistics"],
        "跨 57 个学科的选择题可测量模型在统一设置下的知识与推理表现。",
        "人类和多类语言模型在零样本与少样本设置下的比较。",
        "选择题受提示、污染和猜测影响，不能代表开放式可靠推理。",
        [{"type": "used_by", "target": "llama"}],
        code_url="https://github.com/hendrycks/test",
        reproduction="required-eval",
    ),
    paper(
        "helm",
        "Holistic Evaluation of Language Models",
        2022,
        "2022-11-16",
        "2211.09110",
        ["evaluation", "robustness", "transparency"],
        ["mmlu", "statistics", "benchmarking"],
        "评测应同时覆盖准确性、鲁棒性、公平、校准、效率等多维指标和场景。",
        "统一适配器下对多模型、多场景与多指标的大规模测量。",
        "场景和指标选择仍含价值判断，排行榜聚合会隐藏权衡。",
        [{"type": "contrasts_with", "target": "mmlu"}],
        code_url="https://github.com/stanford-crfm/helm",
        reproduction="required-report",
    ),
    paper(
        "ppo",
        "Proximal Policy Optimization Algorithms",
        2017,
        "2017-07-20",
        "1707.06347",
        ["reinforcement-learning", "ppo", "policy-gradient"],
        ["policy-gradient", "importance-sampling", "kl-divergence"],
        "裁剪概率比可限制单次策略更新并简化信赖域式优化。",
        "连续控制与游戏环境上的样本效率和稳定性比较。",
        "原论文不是语言模型研究；RLHF 中还受奖励建模和序列信用分配影响。",
        [{"type": "used_by", "target": "instructgpt"}],
        code_url="https://github.com/openai/baselines",
        reproduction="toy-policy",
    ),
    paper(
        "constitutional_ai",
        "Constitutional AI: Harmlessness from AI Feedback",
        2022,
        "2022-12-15",
        "2212.08073",
        ["alignment", "rlaif", "self-critique"],
        ["instructgpt", "preference-data", "reward-modeling"],
        "显式原则、自我批评修订与 AI 偏好反馈可减少部分人工有害性标注需求。",
        "红队提示、帮助性和无害性人工评估及训练阶段比较。",
        "原则选择和评审模型会传递偏差，不能替代独立安全验证。",
        [{"type": "improves", "target": "instructgpt"}],
        source_type="technical_report",
        reproduction="self-critique-toy",
    ),
    paper(
        "simpo",
        "SimPO: Simple Preference Optimization with a Reference-Free Reward",
        2024,
        "2024-05-23",
        "2405.14734",
        ["preference-optimization", "reference-free", "alignment"],
        ["dpo", "log-probability", "ranking-loss"],
        "用平均序列对数概率作为隐式奖励，可移除训练时参考模型并控制长度偏置。",
        "多种偏好基准上与 DPO 等方法的质量和效率比较。",
        "参考自由不等于无正则化，超参数和离线数据覆盖仍关键。",
        [{"type": "improves", "target": "dpo"}],
        code_url="https://github.com/princeton-nlp/SimPO",
        reproduction="required-loss",
    ),
    paper(
        "kto",
        "KTO: Model Alignment as Prospect Theoretic Optimization",
        2024,
        "2024-02-02",
        "2402.01306",
        ["preference-optimization", "binary-feedback", "alignment"],
        ["dpo", "prospect-theory", "kl-divergence"],
        "借鉴前景理论的价值函数，可用不成对的好/坏反馈优化语言模型。",
        "不同数据规模和模型上的对话、推理与人类偏好比较。",
        "效用建模是近似，数据类别平衡和 KL 估计会影响稳定性。",
        [{"type": "contrasts_with", "target": "dpo"}],
        code_url="https://github.com/ContextualAI/HALOs",
        reproduction="required-loss",
    ),
    paper(
        "gptq",
        "GPTQ: Accurate Post-Training Quantization for Generative Pre-trained Transformers",
        2022,
        "2022-10-31",
        "2210.17323",
        ["quantization", "post-training", "inference"],
        ["transformer", "hessian", "linear-algebra"],
        "利用近似二阶信息逐列量化，可在无需重训时保持低比特 Transformer 精度。",
        "多类生成模型在 3–4 bit 下的困惑度、速度和量化时间实验。",
        "权重量化不直接减少 KV Cache 和激活，内核支持决定实际加速。",
        [{"type": "builds_on", "target": "transformer"}],
        code_url="https://github.com/IST-DASLab/gptq",
        reproduction="quantize-small",
    ),
    paper(
        "smoothquant",
        "SmoothQuant: Accurate and Efficient Post-Training Quantization for Large Language Models",
        2022,
        "2022-11-18",
        "2211.10438",
        ["quantization", "activation", "int8"],
        ["gptq", "outliers", "linear-layers"],
        "把激活离群难度等价迁移到权重，可实现较准确的 W8A8 训练后量化。",
        "多模型、多任务上的精度、延迟与内存比较。",
        "平滑因子和校准数据影响结果，8-bit 结论不能直接外推到 4-bit。",
        [{"type": "contrasts_with", "target": "gptq"}],
        code_url="https://github.com/mit-han-lab/smoothquant",
        reproduction="required-scale",
    ),
    paper(
        "awq",
        "AWQ: Activation-aware Weight Quantization for LLM Compression and Acceleration",
        2023,
        "2023-06-01",
        "2306.00978",
        ["quantization", "activation-aware", "inference"],
        ["gptq", "activation-statistics", "low-bit"],
        "保护少量由激活统计识别的重要权重通道，可改善低比特权重量化。",
        "多模型与任务上的 3–4 bit 准确率、速度和部署实验。",
        "依赖代表性校准样本和专用内核，重要通道规则不是普适解释。",
        [{"type": "improves", "target": "gptq"}],
        code_url="https://github.com/mit-han-lab/llm-awq",
        reproduction="required-scale",
    ),
]


def main() -> None:
    with CATALOG.open("r", encoding="utf-8") as handle:
        data = yaml.safe_load(handle)
    existing = {item["id"] for item in data["papers"]}
    additions = [item for item in EXTRA_PAPERS if item["id"] not in existing]
    data["papers"].extend(additions)
    data["metadata"]["count"] = len(data["papers"])
    data["metadata"]["policy"] = (
        "Core 约 25 篇；Deep Dive 保持 40–60 篇；新论文先进入 inbox，人工核验后再升级。"
    )
    with CATALOG.open("w", encoding="utf-8", newline="\n") as handle:
        yaml.safe_dump(data, handle, allow_unicode=True, sort_keys=False, width=100)
    print(f"added={len(additions)} total={len(data['papers'])}")


if __name__ == "__main__":
    main()
